name: BuildPocketMobile

on:
  push:
    branches:
      - main
  release:
    types: [created, edited]

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: |
          npm install -g pnpm@latest

      - name: Setup global bin directory for pnpm
        run: pnpm config set global-bin-dir ~/.pnpm-global

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Install Capacitor CLI
        run: |
          pnpm add -g @capacitor/cli

      - name: Initialize Capacitor
        run: |
          npx cap init

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5

      - name: Decode Keystore
        run: |
          echo "${{ secrets.COOKIE_KEY }}" | base64 --decode > ${{ github.workspace }}/cookie.keystore
          chmod 644 ${{ github.workspace }}/cookie.keystore

      - name: Build React App
        run: npx run build

      - name: Sync Capacitor
        run: npx cap sync

      - name: Build Android Packages
        env:
          ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/cookie.keystore
          ANDROID_KEYSTORE_PASSWORD: cookieukw
          ANDROID_KEY_ALIAS: cookieukw
          ANDROID_KEY_PASSWORD: cookieukw
        run: |
          cd android
          ./gradlew clean
          ./gradlew bundleRelease
          ./gradlew assembleRelease
          mv app/build/outputs/bundle/release/app-release.aab app/build/outputs/bundle/release/app-$(date +%Y%m%d%H%M).aab
          mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/app-$(date +%Y%m%d%H%M).apk

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          update: true
          generate_release_notes: true
          files: |
            android/app/build/outputs/bundle/release/*.aab
            android/app/build/outputs/apk/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
